import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://studiovonjenn.com",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
      images: [
        "/images/birds-1.jpg",
        "/images/birds-2.jpg",
        "/images/birds-3.jpg",
        "/images/safara-1.jpg",
        "/images/sara-2.jpg",
        "/images/safara-2.jpg",
        "/images/jennifer-3.jpg",
        "/images/jennifer-2.jpg",
        "/images/jennifer-1.jpg",
        "/images/winter-queen-1.jpg",
        "/images/winter-queen-2.jpg",
        "/images/winter-queen-3.jpg",
        "/images/tiffany-rae-knight-3.jpg",
        "/images/tiffany-rae-knight-2.jpg",
        "/images/tiffany-rae-knight-1.jpg",
        "/images/rozi-1.jpg",
        "/images/rozi-paige-1.jpg",
        "/images/paige-1.jpg",
        "/images/demons-1.jpg",
        "/images/demons-2.jpg",
        "/images/demons-3.jpg",
        "/images/egan-3.jpg",
        "/images/egan-2.jpg",
        "/images/egan-1.jpg",
        "/images/ophelia-1.jpg",
      ],
    },
    {
      url: "https://studiovonjenn.com/portfolio",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
      images: [
        "/images/birds-1.jpg",
        "/images/birds-2.jpg",
        "/images/birds-3.jpg",
        "/images/safara-1.jpg",
        "/images/sara-2.jpg",
        "/images/safara-2.jpg",
        "/images/jennifer-3.jpg",
        "/images/jennifer-2.jpg",
        "/images/jennifer-1.jpg",
        "/images/winter-queen-1.jpg",
        "/images/winter-queen-2.jpg",
        "/images/winter-queen-3.jpg",
        "/images/tiffany-rae-knight-3.jpg",
        "/images/tiffany-rae-knight-2.jpg",
        "/images/tiffany-rae-knight-1.jpg",
        "/images/rozi-1.jpg",
        "/images/rozi-paige-1.jpg",
        "/images/paige-1.jpg",
        "/images/demons-1.jpg",
        "/images/demons-2.jpg",
        "/images/demons-3.jpg",
        "/images/egan-3.jpg",
        "/images/egan-2.jpg",
        "/images/egan-1.jpg",
      ],
    },
    {
      url: "https://studiovonjenn.com/about",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.8,
      images: ["/images/ophelia-1.jpg"],
    },
    {
      url: "https://studiovonjenn.com/prices",
      lastModified: "2025-12-18T14:47:22+00:00",
      changeFrequency: "yearly",
      priority: 0.8,
      images: [
        "/images/galleries/atmos/0126/atmos012610.jpg",
        "/images/safara-1.jpg",
        "/images/galleries/pirate-party-1125/pirateparty11202559.jpg",
      ],
    },
    {
      url: "https://studiovonjenn.com/contact",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://studiovonjenn.com/gallery/atmos2025",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.5,
    },
  ];
}
